const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
const ADD_TO_CART = "ADD_TO_CART";
const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
const CLEAR_CART = "CLEAR_CART";
const SET_USER_ADDRESS = "SET_USER_ADDRESS";
const SET_STATE_PROPERTY = "SET_STATE_PROPERTY";
export {
  SET_LOGIN_STATUS,
  ADD_TO_CART,
  INCREMENT_CART_ITEM,
  DECREMENT_CART_ITEM,
  CLEAR_CART,
  SET_USER_ADDRESS,
  SET_STATE_PROPERTY,
};
